### PR TITLE
Update PHP requirement in troubleshooting guide

### LINKED ISSUE #830: Fix PHP requirement in Troubleshooting guide
https://getkirby.com/docs/guide/troubleshooting/installation#weird-php-syntax-errors

### PR DESCRIPTION
**Pull request by distantnative**
Fixes #830

### CODE REVIEW

**Review by texnixe — COMMENTED** [review]
Didn't we say, support for PHP 7.1 will be dropped from Kirby 3.4 only?

**Comment by distantnative** [comment]
@texnixe We already say on https://getkirby.com/docs/guide/quickstart#requirements that 7.2 is the lowest.

**Comment by texnixe** [comment]
Oh, ok, didn't see that, because my last status was this: https://forum.getkirby.com/t/important-note-on-php-7-4-support/16578/12?u=texnixe

**Comment by distantnative** [comment]
Yea, I just checked the release notes and there it said it as well. Seems like we changed it on the other guide too early.

**Comment by lukasbestle** [comment]
We changed that in #774 to avoid that new users now use 7.1 only to need to upgrade to 7.2 with the next release. Support in the code will indeed be dropped with 3.4.0.

**Comment by lukasbestle** [comment]
I’d suggest to remove the version number from the troubleshooting guide so that we won‘t forget changing it again. The link to the requirements is probably enough.

**Comment by distantnative** [comment]
Updated as suggested by @lukasbestle.

**Review by texnixe — APPROVED** [review]

**Review by lukasbestle — APPROVED** [review]

**Pull request merged**
