### PR TITLE
Releases page

### PR DESCRIPTION
**Pull request by texnixe**
Based on @distantnative's version of the release page, I updated and enhanced it a bit, what do you think?

### CODE REVIEW

**Comment by distantnative** [comment]
I like it 👍 Just the "Further releases" lists blow up the page a lot. Wondering if it could look good to just do them inline, comma separated.

**Comment by texnixe** [comment]
Yes, was wondering that as well

**Comment by texnixe** [comment]
[
Screenshot 2023-03-26 at 21 48 42
](url)

**Comment by distantnative** [comment]
Small tweak suggestion (to get proper commas without spaces): https://github.com/getkirby/getkirby.com/pull/1984

**Review by distantnative — APPROVED** [review]

**Pull request merged**
