### PR TITLE
Author system for the cookbook

### PR DESCRIPTION
**Pull request by bastianallgeier**
It's long-overdue that we have an author system for cookbook articles. Authors are now stored in /content/authors and could be referenced in plugins or themes later as well. 

Each recipe can now define multiple authors in the `Authors` field: 

I.e. 

```
Authors: 

- authors/sonja-broda
- authors/bastian-allgeier
```

Screenshot 2021-04-26 at 14 08 14

New authors can be added easily. 

For now, the authors are below the article. We can change this at any point later. I've added authoring information wherever I was able to find authors or I was able to remember who wrote the article. 

For articles without an author, I simply assumed that Sonja wrote it. That's why the model now uses Sonja as the default. **Please go through the articles and add yourself at those that you wrote.**

### CODE REVIEW

**Comment by texnixe** [comment]
Now auto-assigned to me but definitely not written by me (hope I didn't miss any):

- [x] Setup: Plugin test workflow with PHPUnit (Hristiyan Dodov)
- [x] Setup: Kirby meets Composer (Lukas)
- [x] Setup: Kirby meets Git (Bastian)
- [x] Setup: Monolithic Plugin Setup (Hristiyan Dodov)
- [x] Setup: How to upgrade Kirby 2 plugins (Nico)
- [x] Setup: How to migrate users (Nico)
- [x] Setup: Editable redirects (Nico)
- [x] Translations: Import and export translations (Bastian)
- [x] Content: Sitemap for search engines (Bastian?)
- [x] Content: Random content
- [x] Content: Structure field content
- [x] Content: Related articles
- [x] Content: Search
- [x] Templating: Custom homepage title
- [x] Templating: Art-directed pages
- [x] Templating: Creating a Kirby powered blog
- [x] Templating: One-pager site
- [x] Templating: Generating JSON with Kirby
- [x] Templating: Menus
- [x] Templating: Pagination
- [x] Text: Custom content fields
- [x] Text: Working with dates
- [x] Extensions: A/B testing with Kirby

**Comment by bastianallgeier** [comment]
@texnixe do you think it makes sense to just remove the author block on those articles that we cannot assign properly anymore?

**Comment by lukasbestle** [comment]
If we do want to add the original authors, we can manually find them via the Git history:

1. Go to the recipe's directory on https://github.com/getkirby/getkirby.com/tree/c8e825cfac5b7303fe0f1fb812466f901a96eefe/content/1_docs/2_cookbook
2. Click "History" at the top-right
3. Scroll to the bottom to find the first commit
4. Look who authored it

**Comment by bastianallgeier** [comment]
I'm happy with the current state. If we find some issues later, we can fix them quickly.

**Pull request merged**
