### PR TITLE
Cookbook update

### PR DESCRIPTION
**Pull request by chrfickinger**
Add new section about Laravel Herd to the cookbook recipe "Local development environment"

### CODE REVIEW

**Comment by bastianallgeier** [comment]
This is a great addition, but it seems like another article slipped into this PR :)

**Comment by chrfickinger** [comment]
I sent 2 PRs in 2 different branches. Seem something went wrong, sorry for that. Are you able to merge the 2 PRs?
First PR was a completly new cookbook recipe (with new profile photo)
Second PR was the Laravel Herd addition.

**Comment by texnixe** [comment]
@chrfickinger Could you please create a new PR with only the addition to the Local development environment recipe?

**Comment by texnixe** [comment]
Closing this, because the recipe was already merged.

**Pull request closed without merging**
