### PR TITLE
Cachebusting without rewrite rules

### PR DESCRIPTION
**Pull request by bastianallgeier**

### CODE REVIEW

**Comment by distantnative** [comment]
@bastianallgeier did you mean to delete develop? :D

**Comment by bastianallgeier** [comment]
Argh. Nope. I have no idea how that happened

**Comment by distantnative** [comment]
I think we have activated that successfully merged PRs delete their branch

**Comment by distantnative** [comment]
Screen Shot 2021-04-16 at 18 43 16

**Pull request merged**
