### PR TITLE
Cheat Sheet inheritance improvements

### PR DESCRIPTION
**Pull request by lukasbestle**
- [x] Added a route that will parse virtual URLs of now inherited cheat sheet items; this makes the links work again
- [x] Implemented that new route to be used in cheat sheet links instead of the actual URL with a param
- [x] Updated sidebar to behave like an item page wasn't inherited (displays links to "virtual" parent)

**Now done**:

- [x] Make the prev and next links in the sidebar support both inherited and actual items: Only displays inherited ones for inherited pages and actual ones for actual pages right now.

### CODE REVIEW

**Comment by lukasbestle** [comment]
Finally found a solution for the cheat sheet item sidebar. This PR is now done and needs to be tested.

**Comment by texnixe** [comment]
Great, I'll check it out tonight :-)

**Comment by distantnative** [comment]
Just matched the `ready` label with the ones used for the `panel` and `kirby` repos.

**Comment by lukasbestle** [comment]
:+1:

**Comment by lukasbestle** [comment]
Fantastic, thanks! :+1:

**Pull request merged**
