### PR TITLE
Add Ahmet to team page

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by afbora** [comment]
Just a suggestion: It would be better if the links in team and contributors are opened in new tab with `rel=nofollow`?

**Comment by distantnative** [comment]
I think in terms of accessibility it's always better to let the user choose if to open in same tab or new tab.

**Review by afbora — APPROVED** [review]
❤️

**Comment by bastianallgeier** [comment]
@afbora so good to finally have you on the team page!

**Pull request merged**
