### PR TITLE
Favicons & OpenGraph/Twitter metas.

### PR DESCRIPTION
**Pull request by AhoyLemon**
Not sure if this was left out intentionally, but...

Today I posted getkirby.com to a slack channel and noticed the site had no meta information. I've been doing a whole lot of that lately, so I thought I'd suggest a plan for implementing that on the site. 

This pull request has all the neccessary information for OpenGraph as well as Twitter, plus it has the full (absurd) favicon stack provided by [Real Favicon Generator](http://realfavicongenerator.net/), taken from the AI file, this comes in a whole bunch of sizes plus it's got a transparent background.

Hope that's useful.

### CODE REVIEW

**Comment by JimmyRittenborg** [comment]
**Image Compression **

My compression OCD kicked in :laughing:
Brought it down from 43.629 bytes to 15.978 bytes without any noticeable loss in quality.

[compressed-favicons.zip](http://cl.ly/0r1m2h3b3z2k)

**Comment by AhoyLemon** [comment]
Good catch, @JimmyRittenborg. Is that 43b for the whole stack?

**Comment by JimmyRittenborg** [comment]
@AhoyLemon yes, both numbers is for the entire stack of images :yum:

**Comment by JimmyRittenborg** [comment]
You should check out [ImageAlpha](https://pngmini.com) for lossy but still not visible compression of transparent PNGs in conjunction with [ImageOptim](https://imageoptim.com) for lossless compression of PNGs and all the rest.

I only suggest this pretty manual lossy approach for transparent PNGs as there's better and more automating friendly stuff out there for JPEGs.

For the SVG I used [svgo](https://github.com/svg/svgo) and some common sense in manually removing svg version attribute and unnecessary decimals in from the viewbox attribute.

**What I didn't do was checking if the PNGs without any transparency was smaller if the were converted to JPEGs, it wouldn't surprise me as JPEG is way better for compression also gzip than PNG, I'll leave that one for yourself.**

**Comment by AhoyLemon** [comment]
Makes sense. @JimmyRittenborg, feels like half of this stuff is automated, have you thought about reaching out to [Real Favicon Generator](https://github.com/RealFaviconGenerator) to improve the graphics they serve up?

**Comment by JimmyRittenborg** [comment]
@AhoyLemon to be honest I'm really not a fan of using and relying on some website for bundling png's in a .ico container beside this problem, the rest is only plain and simple images and specifications.

And what I also think, is that we might need to ensure that most of all this stuff really isn't redundant and a complete overkill to include - as a starting reference see this https://github.com/audreyr/favicon-cheat-sheet

**Comment by AhoyLemon** [comment]
Well, that's not what RFG does. It's just a little site where you give it a high res image and it spits out the 40,000 different favicons you need as well as the relevant meta tags.

**Pull request closed without merging**
