### PR TITLE
Add Colors and Tree Method plugins

### PR DESCRIPTION
**Pull request by nilshoerrmann**
This updates our plugin informations, adding new pages for `kirby-colors` and `kirby-tree-methods`.

### CODE REVIEW

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
It would be lovely to have a nice screenshot for the colors plugin. The ones in the Github repo are a bit too small I think.

**Comment by nilshoerrmann** [comment]
What kind of bigger screenshot do you imagine? And how do I provide it best?

**Comment by bastianallgeier** [comment]
The format should be similar to this: https://getkirby.com/plugins/sylvainjule/autofocus

Maybe you can arrange a couple different field setups in a nice grid (3 x 3 or 2 x 2 color fields) and make a screenshot of that. 

Kirby will pick up everything that is called screenshot.(png|gif|jpg) in the same folder as the plugin.txt

**Comment by nilshoerrmann** [comment]
Okay, I'll try to take a look into that next week.

**Pull request merged**
