### PR TITLE
kirby-stripe plugin

### PR DESCRIPTION
**Pull request by tristantbg**

### CODE REVIEW

**Comment by afbora** [comment]
@tristantbg Your plugin registry is inconsistent like `tristantbg/kirby-stripe`, `tristanb/kirby-shopify` and your getkirby vendor name is `tristanb`. I think getting it all in order would be great for users to keep up with updates.

**Comment by afbora** [comment]
@tristantbg I think just updating `kirby-stripe` plugin vendor name to `tristanb` seems enough

**Comment by tristantbg** [comment]
@afbora  I never created this tristanb folder and there was also a problem with kirby-shopify plugin at that time.
Maybe we should rename the kirby folder to tristantbg ?

**Comment by afbora** [comment]
@tristantbg I can update your vendor name in getkirby but your `shopify` plugin registry name is `tristanb/kirby-shopify` and you need to update with `tristantbg/kirby-shopify`.

**Comment by afbora** [comment]
@tristantbg I've updated your vendor name. Now you should always use `tristantbg/*` in the registry name of plugins.

**Comment by tristantbg** [comment]
> @tristantbg I've updated your vendor name. Now you should always use `tristantbg/*` in the registry name of plugins.

Ok thanks !

**Pull request merged**
