### PR TITLE
$page->sort() without parameter, fix #184

### LINKED ISSUE #184: Calling $page->sort() without parameter
... works as alias for $page->num()

### PR DESCRIPTION
**Pull request by distantnative**
**Please do not merge before the release of 2.3**

### CODE REVIEW

**Comment by lukasbestle** [comment]
Could you please send your PRs to the `develop` branch again? We could then merge them before the release.

**Comment by distantnative** [comment]
Problem is that we haven't kept the `develop` branch really up-to-date. We should then merge all the changes from the master branch first (since they are not just single edits, but pretty fundamental changes).

**Comment by lukasbestle** [comment]
Well, we do. The master branch gets changes for the current Kirby version, the develop branch ones for the next version. But you are right, we should regularly merge the changes from the master branch back. I have just rebased the develop branch.

**Comment by distantnative** [comment]
:+1:

**Pull request closed without merging**
