### PR TITLE
Enhancements to release page

### PR DESCRIPTION
**Pull request by lukasbestle**
Here's the first round of my suggestions for the release page.
I didn't find the time to look at the updated release notes yet. Will do so tomorrow morning.

What I noticed is that the tables in the Core Refactoring and Deprecated sections are too narrow for the many columns. IMO we either need to replace the tables with a different layout element or make these two sections full-width.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I don't really mind that the table scrolls sideways tbh.

**Comment by lukasbestle** [comment]
It's fine regarding layout and design, but for actually reading it I think it's not optimal.

**Comment by bastianallgeier** [comment]
@lukasbestle totally! It's a trade-off. What about moving version number and throws columns to the right? They are not that important at all.

**Comment by lukasbestle** [comment]
For these tables, yes. I think "Use instead" should be the second column.

There's also "Namespace changes", but it's just about fine still. At least on larger displays.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
