### PR TITLE
Add limitations and workarounds with TailwindCSS

### PR DESCRIPTION
**Pull request by anselmh**
I edited the page because I was missing information and [it seems I’m not the first](https://forum.getkirby.com/t/css-classes-in-writer-output/20745). Feel free to edit, adjust or merge.

Generated output can’t easily be used with TailwindCSS so this documents the limitations and provides some ideas for available workarounds.

### CODE REVIEW

**Comment by distantnative** [comment]
@chrfickinger same here since this was your original recipe

**Comment by anselmh** [comment]
Do you have any preference / idea of how to deal with this now? I would be able to extend the documentation further but since this one is stale since months I’m not sure if it’s worth the effort.

For example I could add https://helloanselm.com/writings/quick-tailwindcss-production-setup and https://helloanselm.com/writings/using-tailwind-within-css.

**Comment by texnixe** [comment]
@anselmh Yes,  would be great if you can extend this a bit. Maybe also mention the typography plugin which might be useful in block contexts. I think it's mentioned in one of your articles.

**Comment by texnixe** [comment]
I'll merge the current state, then we can add to it when you get round to it.

**Review by texnixe — APPROVED** [review]

**Comment by texnixe** [comment]
Changes added via a new branch

**Pull request closed without merging**
