### PR TITLE
Ignore editors

### PR DESCRIPTION
**Pull request by afbora**

### CODE REVIEW

**Comment by lukasbestle** [comment]
If we do this, we also need to explicitly delete the `.vscode` directory in a commit, otherwise the `.gitignore` won't have an effect on it.

**Comment by afbora** [comment]
How can I do that? Because I'm using PhpStorm.

**Comment by lukasbestle** [comment]
You can just delete the `.vscode` folder in your file manager. Git will then see the change and offer to commit the deletion to the PR.

**Comment by afbora** [comment]
I didn't realize it had the `.vscode` folder because I was using PHPStorm 😅

**Review by lukasbestle — APPROVED** [review]

**Comment by afbora** [comment]
👉  Would it be okay for you to ignore IDE files/folders? @bastianallgeier @distantnative @texnixe

**Review by bastianallgeier — APPROVED** [review]

**Comment by bastianallgeier** [comment]
Yep, totally fine for me.

**Comment by afbora** [comment]
🎉 Thank you

**Pull request merged**
