### PR TITLE
Consistent license hub links

### PR DESCRIPTION
**Pull request by distantnative**
- Added license hub links to license terms
- Using `hub.getkirby.com` throughout site

### CODE REVIEW

**Comment by bastianallgeier** [comment]
What's your reasoning behind the changes? I thought we decided to go for hub.getkirby.com a while ago.

**Comment by distantnative** [comment]
We can also go for the hub one - just think it should be one consistent URL and not both in different places.

Couldn't remember that decision. To me licenses felt more self explanatory also for users later.

**Comment by bastianallgeier** [comment]
@distantnative I agree that it should be consistent. I think the general idea was that the hub could and should go beyond just licenses later. That's why we chose hub instead of licenses.

**Comment by distantnative** [comment]
@bastianallgeier changed it

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
