### PR TITLE
feat: add query template to form field placeholder description

### PR DESCRIPTION
**Pull request by pReya**
* add query template hint to form fields parameter description (see https://github.com/getkirby/kirby/pull/2029/files)

### CODE REVIEW

**Comment by pReya** [comment]
Hmm, I just discovered, this is now supported on `before`, `after`, `default`, `label` and `placeholder`. Should I add the sentence to all these params? Or will this look repetitive? Is there a better way to indicate that query templates are supported on these params?

**Comment by texnixe** [comment]
I'm sorry, this is the wrong repo for this PR, this need to go into the kirby repo.

**Comment by pReya** [comment]
Sorry, I never looked at the structure of the documentation repo. Now I see that it just uses a regular Kirby instance and uses the comments from the Kirby folder. I'll submit a PR to the other Repo. But since you're the documentation queen @texnixe, do you have any advice on my question? Is it a good idea to copy & repeat the given sentence after every param that supports query templates? Or is there a better way?

**Comment by distantnative** [comment]
I think we're starting to repeat this too often then. Probably rather need to add a general part somewhere about this feature. What do you think @texnixe?

**Comment by distantnative** [comment]
Closing this for the other approach we discussed on Discord

**Pull request closed without merging**
