### PR TITLE
Docs for Kirby 3.5.5

### PR DESCRIPTION
**Pull request by lukasbestle**
✅ = Documented on the `release/3.5.5` branch

| ✅ | Issue/Feature | Related PR | Assignees | Documenting Commit |
| :-- | :--| :-- | :-- | :-- |
| ✅ | Configurable menu entry for views | https://github.com/getkirby/kirby/pull/3206 | @lukasbestle | 887b5e63104a6c930be497637387b505428d0f01 |
| ✅ | Cache (expiry) in `$kirby->response()` | https://github.com/getkirby/kirby/pull/3246 https://github.com/getkirby/kirby/pull/3292 | @lukasbestle  | 887b5e63104a6c930be497637387b505428d0f01 |
| ✅ | User language in email auth challenge | https://github.com/getkirby/kirby/pull/3294 | @lukasbestle  | 887b5e63104a6c930be497637387b505428d0f01 |
| ✅ | Pass exception to fatal error handler | https://github.com/getkirby/kirby/pull/3270 | @bastianallgeier | 887b5e63104a6c930be497637387b505428d0f01 |
| ✅ | Video kirbytag supports local and remote videos | https://github.com/getkirby/kirby/pull/3277 | @afbora | 67bcd6dccead049e405635f9958cd7192c1043c0 |

### CODE REVIEW

**Comment by afbora** [comment]
@lukasbestle I updated the document about the new video tag. Can you check if I ask? 🙏

**Comment by lukasbestle** [comment]
@afbora Thanks! I've restructured the page a bit as it got a bit confusing the more information we added to it over the last versions. The content is great!

**Comment by afbora** [comment]
@lukasbestle Great touch! 👍 Also could you update `intro` of the page please? `Embeds a YouTube or Vimeo video by URL`

**Comment by lukasbestle** [comment]
Good point. ✅

**Pull request merged**
