### PR TITLE
$page->sort() without parameter, fix #184

### LINKED ISSUE #184: Calling $page->sort() without parameter
... works as alias for $page->num()

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by lukasbestle** [comment]
Generally great, but please add the new default param to the title.

**Comment by distantnative** [comment]
Arg sorry, got lost in the web edit.

**Comment by lukasbestle** [comment]
Alright, thanks.
Another small issue: Please use a `h3` for the new heading so that the heading levels are correct. But then it should be fine. :)

**Comment by distantnative** [comment]
Not same like Example?

**Comment by lukasbestle** [comment]
Oh, I'm sorry. You are of course right!

Thanks. :+1:

**Comment by bastianallgeier** [comment]
Yay, notification terror \o/ Keep it coming :)

**Comment by lukasbestle** [comment]
Now you know how we are feeling when you are on a merging spree. :P

**Comment by bastianallgeier** [comment]
I knew it was all about revenge :P

**Pull request merged**
