### PR TITLE
docs: add cookbook recipe for nginx

### PR DESCRIPTION
**Pull request by pReya**
* add cookbook article for nginx configuration
* reasoning: there's currently very little information on how to run Kirby on nginx. only a couple of posts on the forum with partially correct solutions. hope this recipe can be a better source for people looking for info on this topic.
* the "line-by-line explanation" part looks very text-heavy – i think it could use more whitespace – any ideas?

### CODE REVIEW

**Comment by texnixe** [comment]
Great, been wanting this for a while! I pushed some little typo fixes.

**Comment by pReya** [comment]
@texnixe Are you sure, you pushed them? Can't see any new commits from you.

**Comment by texnixe** [comment]
@pReya The PR ended up in your cloned repo 🙈 . There is also one here, but I couldn't make a merge request against your PR

**Comment by afbora** [comment]
@texnixe I've pushed [the commit](https://github.com/getkirby/getkirby.com/pull/1360/commits/6f874e29e0af8d9c0303d30f20db2f1672123b45) your changes to directly @pReya's branch manually.

**Comment by texnixe** [comment]
@afbora Thanks a lot.

**Pull request merged**
