### PR TITLE
Add lukaskleinschmidt plugins

### PR DESCRIPTION
**Pull request by lukaskleinschmidt**
Let me know if the example for the types plugin is too much

### CODE REVIEW

**Comment by lukasbestle** [comment]
The code examples are used in the plugin's card and room is very limited. You can preview how it will look like by setting up this repo on your local dev server.

**Comment by lukaskleinschmidt** [comment]
I did. And it works well I would say. Was just not sure about adding a custom css animation is something you would want to add

**Comment by texnixe** [comment]
I know it's not documented yet, but could you also please add a `published` field (Published: 2023-04-04), so that the plugin appears in the `new` category? Thanks!

**Review by lukasbestle — COMMENTED** [review]
Thanks for adding the metadata. 👍

Just looked closer at the code example of the types plugin and tested it locally. Now I know why it fits into the preview card. 🤯
It's a nice idea to use highlighting and the animation. However I feel like the animation would be too distracting if other plugins also used animated cards. Also the text colors don't really fit with the site colors.

So I suggest the following: No animation and colors from the CSS variables. Would that be fine for you?

**Comment by lukaskleinschmidt** [comment]
Works for me :)

**Comment by lukasbestle** [comment]
Thanks. 👍

**Pull request merged**
