### PR TITLE
Add `email` to the available writer marks

### PR DESCRIPTION
**Pull request by timnarr**
Small doc improvement... Added `email` as a available format to the writer marks.

### CODE REVIEW

**Comment by distantnative** [comment]
@afbora does this refer to this change? https://getkirby.com/releases/3.6/features/email-writer-dialog
Then it would only be in 3.6

Also @TimGr we don't edit the core files (everything in `kirby/` folder) in this repo as we use a standard kirby installation to run the site. We would need to make that change in https://github.com/getkirby/kirby

**Comment by timnarr** [comment]
Ah, I see thanks for the hint @distantnative 
I'm currently working on a site that runs `3.6.0-rc.1` and that's where I noticed this. So maybe you're right that this refer to the mentioned change

**Comment by afbora** [comment]
@distantnative Yes, I've created PR for it: https://github.com/getkirby/kirby/pull/3835

**Comment by afbora** [comment]
Also I've added to 3.6 docs: https://github.com/getkirby/getkirby.com/pull/1420

**Comment by bastianallgeier** [comment]
✅

**Pull request closed without merging**
