### PR TITLE
Tweak docs font sizes and gaps

### PR DESCRIPTION
**Pull request by distantnative**
@bastianallgeier @texnixe 
Trying a simple fix for getting more compact docs.

I know that this could rub Basti in a wrong way regarding overall consistency across the whole site, but I think since that would require quite a bit of time, this seems to me like it could be a good compromise for effort and benefit.

### CODE REVIEW

**Comment by texnixe** [comment]
@distantnative I like it.

**Comment by distantnative** [comment]
Great! Lege See what @bastianallgeier thinks.

The new article.css file annoys me a bit with just one rule in there.

**Comment by bastianallgeier** [comment]
I like the direction, but I really get nervous with the headline size changes. I don't think they are helping as much as they feel weird when jumping from other pages. I would rather focus some more on optimizing the prose css even more.

**Comment by distantnative** [comment]
You mean the top headline? I think they are way too big in the docs and just take up screen space without adding much information ("Guide"). Also from most of the other pages the layout shifts anyways a lot to the docs, so I wouldn't see it as an issue. Or we decrease the title size also on those other pages.

**Comment by bastianallgeier** [comment]
I think it's a good idea to simply reduce the font size everywhere to keep it consistent

**Comment by distantnative** [comment]
@bastianallgeier I've globally tweaked the large text sizes instead now

**Comment by bastianallgeier** [comment]
@distantnative great change! I went through most of the pages and it seems to work really well across the board. I think we need to keep adjusting intro blocks and other parts next, but those are really just minor details.

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
