### PR TITLE
Additions to the "Beyond Kirby" guide

### PR DESCRIPTION
**Pull request by lukasbestle**
From this discussion on Discord: https://discord.com/channels/525634039965679616/978572175013470218/979339042812477450

I've also added an info box on "headless use of headless tech". Please let me know what you think, maybe it's too extreme.

### CODE REVIEW

**Comment by texnixe** [comment]
Great additions, what I'm not so happy with are the modified heading levels. A TOC where the possible approaches are visible seems more useful to me.

**Comment by texnixe** [comment]
> The technologies and approaches we describe here have very valid uses as we showed above. Please use them wisely and not ... *headless*. 🙂

This could come across as a bit paternalistic?

**Comment by lukasbestle** [comment]
> A TOC where the possible approaches are visible seems more useful to me.

Good point. The reason I changed it was to add the "Approaches for 'headless' Kirby" heading (to make the first intro section shorter and easier to read). I thought that it makes sense from the semantics that the different approaches are now subheadings. But I agree with you that the missing TOC is not great.

I can reverse the heading level changes so that the options are on the same level as the "Approaches" heading.

> This could come across as a bit paternalistic?

That's what I thought as well. I still think we should bring our opinion on this topic across. How can we phrase it better?

**Comment by texnixe** [comment]
Maybe just turn the argument around, then we don't need the advice at the end?

The technologies and approaches we describe here have very valid uses as we showed above. 

Sometimes, however, "headless" technologies are used for their own sake, for example to satisfy a buzzword-driven project requirement or to reduce the (perceived) development effort. This is often at the cost of performance (due to additional requests, JS code and frontend calculations), accessibility (due to issues with semantics), efficiency (due to a higher energy usage) and therefore at the cost of the overall user experience.

**Comment by lukasbestle** [comment]
I like it. 👍

**Pull request merged**
