### PR TITLE
Version badges: first implementation

### PR DESCRIPTION
**Pull request by distantnative**
As a starting point for a discussion for #173.

Def needs better CSS. Potentially also a better way to link to changelogs than filtering by the title.
And I have been wondering how we would deal with it over time. Some pages would be plastered with version badges for each new paragraph.

### CODE REVIEW

**Comment by texnixe** [comment]
> Some pages would be plastered with version badges for each new paragraph.

That doesn't make sense. If this really happens, we would have to restructure the docs, either write version based tutorials or write different chapters for different versions. Or throw old stuff away.

**Comment by lukasbestle** [comment]
I really like the implementation!

As you wrote, the CSS still needs some work (most importantly the link styling inside the version label box). Another small detail: I'd use the wording "Since Kirby 2.2" instead of "Since 2.2" to make it a bit more clear.

Aside from that: Good work!

**Comment by distantnative** [comment]
>  I'd use the wording "Since Kirby 2.2" instead of "Since 2.2" to make it a bit more clear.

Sounds good. Wondering if the field for `cheatsheet.item.txt` should be called `Version:` (as it is now) or rather `Since:` for more consistency?

Also, instead of trying to re-engineer the link to the correct changelog, should we just pass it? OR do you have an idea for a more robust way of figuring out the URL?

**Comment by distantnative** [comment]
> @texnixe:
> That doesn't make sense. If this really happens, we would have to restructure the docs, either write version based tutorials or write different chapters for different versions. Or throw old stuff away.

Yea probably. Or just make a cut and assume that we really only need to highlight additions from the last version. Or last two or so.

**Comment by lukasbestle** [comment]
> Wondering if the field for cheatsheet.item.txt should be called Version: (as it is now) or rather Since: for more consistency?

I agree. +1 for `Since`.

> OR do you have an idea for a more robust way of figuring out the URL?

We could introduce a new "Version" field for the changelog entries that just contains something like `2.3.0`. That would make it possible to use exact matching.
Concerning "short versions" like `2.2`: If the `since` field/Kirbytag only contains one dot, we add `.0` at the end.

**Comment by distantnative** [comment]
Sounds good! Will try to implement it later or tomorrow.

**Comment by distantnative** [comment]
Improved/Refactored a bunch of things around the since badges. If you have better styling CSS, bring it on :laughing:

**Comment by distantnative** [comment]
Noticed that atm it can still break the ToC plugin because of it's automatic generation (if a `since` Kirbytag is used in a heading)

**Comment by distantnative** [comment]
If I put the Kirbytag inside a paragraph, e.g. like

```
This function has been present (since: 2.2) to
````

or at the beginning

```
(since: 2.2) this also
````

Everything after the tag in the paragraph disappears. Have you any idea why?

**Comment by lukasbestle** [comment]
The "rest of line" bug has been reported somewhere else before, but I can't find it right now.

**Comment by texnixe** [comment]
I tested the tag in a fresh install and no problem. But a similar problem was described with the email tag [in this forum thread](https://forum.getkirby.com/t/email-tag-not-parsed-correctly-when-it-is-last-element-of-textarea/2866).

**Comment by bastianallgeier** [comment]
This is so cool! I never really thought about having tags for paragraphs or headlines, but this makes perfect sense. Should I work a bit on the styling? 

For the cheatsheet links, I think we should just support the latest format: {date}-kirby-{version} The date can be ignored anyway and the rest is easy to link to. For those changelog entries, which fall out of this format, the link will just be missing. No big deal if you ask me, as long as we keep in mind that all future changelog entries have to stick to the same format. 

I don't really understand what's going on with that weird bug. Regex is sometimes really killing me :(

**Comment by distantnative** [comment]
@bastianallgeier always happy about better styling :)

Will try to investigate further where that weird bug is coming from.

**Pull request closed without merging**
