### PR TITLE
Designers page: Add section on white-labeling

### LINKED ISSUE #1414: Add white-label Panel interface as feature
That our Panel is basically a white-label solution is a big feature that often comes at extra costs with other systems. We don't sell it on our site at all.

### PR DESCRIPTION
**Pull request by lukasbestle**
Closes #1414.

**Open question:** As far as I can tell, it's currently not possible to set a custom favicon for the Panel. This would be the missing piece for a fully white-label solution.

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I would still remove the favicon sentence and just get that fixed in 3.6 with a panel.favicon config option.

**Comment by lukasbestle** [comment]
I think we should mention the favicon. We can't really say "there isn't any branding whatsoever by default".

👍 on the `panel.favicon` option for 3.6: https://github.com/getkirby/kirby/issues/3516

**Comment by distantnative** [comment]
I'd remove that favicon sentence part. It reads weird in there - moving from the big inspirational picture to a tiny detail. I think there are a lot of solutions out there as "white-labeled" that ship with some defaults that easily can be deactivated. Our only thing is the favicon which will be deactivatable in 3.6 - I think nobody except us would blame us for stating "there is no branding".

**Comment by lukasbestle** [comment]
You are right, other companies would be even more aggressive on their marketing pages. I rephrased it a bit. :)

**Review by distantnative — APPROVED** [review]

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
