### PR TITLE
Append permission pitfall

### PR DESCRIPTION
**Pull request by scsskid**

### CODE REVIEW

**Comment by distantnative** [comment]
Instead of setting permissions for the whole Kirby folder, wouldn't it bet better to create the media folder and set permissions for it?

**Comment by scsskid** [comment]
I guess you are right

maybe link to existing docs where is stated which folders are written to?

site/cache
site/sessions

...

?

**Comment by distantnative** [comment]
@texnixe do we have those listed somewhere? I can't find anything.

**Comment by texnixe** [comment]
@distantnative Doesn't look like we have such a list in the docs, although the Panel checks at installation if these folders are writable (although the cache folder is not part of the check, no idea why).

**Comment by scsskid** [comment]
I narrowed it down to:

/media
/content
/site/sessions
/site/accounts
/site/cache

**Comment by texnixe** [comment]
@scsskid Yes, those are the ones. That these folders are writable, is a general requirement though, not limited to the nginx cookbook recipe.

**Comment by scsskid** [comment]
fair enough, closing

**Pull request closed without merging**
