### PR TITLE
update docs, window should be window/tab

### PR DESCRIPTION
**Pull request by joereynolds**

### CODE REVIEW

**Comment by texnixe** [comment]
`target:_blank` opens a link either in a new window or in a new tab depending on your browser/browser settings.

**Comment by joereynolds** [comment]
In that case should it read 'window/tab'? Happy to change it

**Comment by texnixe** [comment]
Yes, window/tab would be fine.

**Comment by texnixe** [comment]
Thanks for your support to improve the docs.

**Pull request merged**
