### PR TITLE
Cookbook author template

### LINKED ISSUE #1357: Cookbook: author recipes
When we click on the author in the recipe, the author's other articles will be listed instead of going to the website.

### PR DESCRIPTION
**Pull request by distantnative**
Not the prettiest, but a start

Screen Shot 2022-03-21 at 11 47 04

Fixes #1357

### CODE REVIEW

**Review by afbora — APPROVED** [review]
I liked that, thanks 💛

**Comment by distantnative** [comment]
Or maybe a bit more reduced for the start?

Screen Shot 2022-03-21 at 15 07 21

**Comment by texnixe** [comment]
I think it would be nice to have the author image, but the card style at the top is probably not so ideal. Maybe a mix of 1 and 2.

**Comment by distantnative** [comment]
Screen Shot 2022-03-21 at 15 16 53

**Comment by texnixe** [comment]
Maybe put it either below or at least so that both headlines are aligned.

**Comment by distantnative** [comment]
Haven't had a good idea how to put it below. Just looks really weird. And aligning the headlines is hard, but I think it's better now what I pushed to the PR.

**Pull request merged**
