### PR TITLE
Reference refactoring

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Review by afbora — COMMENTED** [review]
I found only one issue about `All classes` menu. Maybe it just might not work on my local.

**Menu:** Advanced > All classes
**Url:** /docs/reference/@/classes
**Error:** Call to a member function url() on bool

image (1)

**Comment by distantnative** [comment]
@afbora Good catch. Just pushed a fix for that.

**Comment by afbora** [comment]
Now works great!

---

I found another one. I will do a more general scan.

Please check the url: /docs/cookbook/extensions/extending-kirbytags

> Call to a member function title() on null

**Comment by distantnative** [comment]
Fixed. 

But agreed, I will also try to do a thorough scan throughout the whole site.
But as always is the case: more eyes see more. Thanks!

**Comment by distantnative** [comment]
@afbora Is it for you possible to run `nom run build` on this branch? On my current setup I am running into errors.

**Comment by afbora** [comment]
@distantnative Yes, i have errors too

````
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\webpack\bin\webpack.js ENOENT
    at notFoundError (\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! getkirby.com@3.0.0 build: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the getkirby.com@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     \AppData\Roaming\npm-cache\_logs\2020-08-25T12_21_59_386Z-debug.log
openssl config failed: error:02001003:system library:fopen:No such process
````

**Comment by afbora** [comment]
@distantnative Working properly for me.

> 95% emitting DONE  Compiled successfully in 18165ms15:42:02

_Note: I just wrote first that it gave an error because I didn't run `npm install` 🙈_

**Comment by distantnative** [comment]
@afbora Could you send me the dist folder? It's not working for me and this PR needs one little CSS change I made

**Comment by afbora** [comment]
@distantnative `/www/assets` folder sent via Slack

**Comment by distantnative** [comment]
Closing for now, will open revived one again.

**Pull request closed without merging**
