### PR TITLE
Added fieldoptions from field docs

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by lukasbestle** [comment]
Thanks for the PR, looks great. :+1: 

One small issue: The examples for radiobuttons and select are the same as for checkboxes.

**Comment by distantnative** [comment]
And I thought I had it all... fix coming.

**Comment by lukasbestle** [comment]
Thanks! :+1:

**Comment by distantnative** [comment]
Not sure if this already should have been merged? It's only on the develop branch so far.

**Comment by bastianallgeier** [comment]
nope, shouldn't be merged before the release is done. could you revert it?

**Comment by lukasbestle** [comment]
Very true. I will create a develop branch of the Kirby site and add the changes to that.

**Pull request merged**
