### PR TITLE
Fix Typographer plugin content file

### PR DESCRIPTION
**Pull request by nilshoerrmann**
See #2042

### CODE REVIEW

**Comment by texnixe** [comment]
I solved this directly, this PR could not be merged due to conflicts.

**Comment by nilshoerrmann** [comment]
Thanks! And sorry, not sure what happened there.

**Comment by texnixe** [comment]
No worries, maybe you didn't pull the latest changes before pushing.

**Comment by nilshoerrmann** [comment]
I actually did but via the Github web interface – will keep away from that next time :)

**Pull request closed without merging**
