### PR TITLE
Add docs for table block, adapt template

### PR DESCRIPTION
**Pull request by texnixe**

### CODE REVIEW

**Review by afbora — APPROVED** [review]
It's good to see missing blocks for a long time 👍

**Comment by distantnative** [comment]
Instead of the if statement for a specific page, I think we should use different field names for the two positions

**Comment by distantnative** [comment]
@texnixe shall we change this still?

**Comment by texnixe** [comment]
@distantnative Feel free, I don't quite understand what you mean with those different field names.

**Comment by distantnative** [comment]
@texnixe I think it's bad practice if we start adding if-statements for one specific page in the templates, if the name changes or another page with the same needs comes up, this will get quite messy. So I thought, if you really want this text not in the standard position, we could add a `conclusion` field in addition to the `text` field which then gets output at the different position.

**Pull request merged**
