### PR TITLE
Add docs about deletable setting for blueprints

### PR DESCRIPTION
**Pull request by malvese**
"Example blueprints" remains the last entry in this section, hence the renaming/sorting of folders.

### CODE REVIEW

**Comment by distantnative** [comment]
Wouldn't it make more sense to add this information to the `Page Settings` page (http://getkirby.com/docs/panel/blueprints/page-settings) instead of creating a new page just for the `deletable` option?

**Comment by texnixe** [comment]
I agree, I would put that in page settings as well.

**Comment by malvese** [comment]
Yes, but as I explained [in the forum](http://forum.getkirby.com/t/undocumented-kirby-features/843/3?u=malvese) it is a blueprint setting not a pages: setting. I fear lots of people would indent it the wrong way if it is included in the Page settings.

**Comment by texnixe** [comment]
I see what you mean, the page settings are really just subpage settings ... and there is no page for page/blueprint settings ...

**Comment by malvese** [comment]
AFAIK, there are only 2 blueprint settings: preview and deletable. We could groups them but under what name?
Perhaps rename "Page settings" -> "Subpages settings" ;
And put preview and deletable into "Page settings"?

Tricky.

**Comment by texnixe** [comment]
Well, I would regard "files" and "pages" as blueprint settings as well?

**Comment by malvese** [comment]
Ah, yes, in a way.
My reasoning was, apart from `title` which describes the blueprint itself, we have 2 kinds of settings:

- those that apply to the page created using this blueprint (`deletable`, `preview`), i.e. `deletable: true` doesn't make subpages un-deletable.
- those that apply to how "children" of these pages are displayed ((sub)`pages`and `files`)

**Comment by texnixe** [comment]
Well, yes and no, IMHO "pages" defines if the page created by using this blueprint, can have pages or not and if so, indented under this setting, what templates these subpages can use etc. And the same is true for files, you first define if the page may have files before defining these files in the indented settings.

**Comment by malvese** [comment]
Makes sense!  We then have 5 settings for pages using a blueprint:
- `pages:`
- `fields:`
- `files:`
- `preview:`
- `deletable:`
The first 4 have a dedicated page, so adding one for `deletable` seems logical to me, even if there's not much to write for now.
I still think the title "Page settings" is misleading, and should be renamed (to "Subpages settings"?)

**Comment by distantnative** [comment]
I see, I overlooked that on posting my comment.

What would you think about renaming it to `Subpages settings` and then merge `preview` and `deletable`  to a new `Page settings` page? I'd think that we might see more options that could go there in the future.

**Comment by malvese** [comment]
Yes, seems like a good solution to me.

**Comment by distantnative** [comment]
Do you wanna do the pull request yourself? Otherwise I'll prepare one

**Comment by malvese** [comment]
Yes, I'll update it in a moment. It's a way to get more familiar with how the docs are structured, for future contributions ;)

**Comment by malvese** [comment]
Quick question: when I rename a page, like "Page settings", do I modify the slug too?
(got caught up in that thing they call work)

**Comment by distantnative** [comment]
I would say yes :+1:

**Comment by malvese** [comment]
Reordered the sections a bit to have fields first, then what's in the sidebar for panel users from top to bottom.
- Setting the blueprint title
- Form Fields
- Page settings
- Subpages Settings
- File Settings
- Example blueprints

The existing docs use "file" (singular) and "subpages" (plural), I don't know if there is a reason so I didn't mess with the existing content.

**Pull request merged**
