### PR TITLE
Texnixe/home release update

### PR DESCRIPTION
**Pull request by texnixe**
Add button text/link based on `$kirby->version()`.
I rebased this on main, maybe it makes more sense to merge directly into main.

### CODE REVIEW

**Comment by distantnative** [comment]
@texnixe Do you want to open a new PR with your stuff directly to `main`? I think we can better review that than trying to merge it into my ancient PR.

**Comment by texnixe** [comment]
I changed the base, doesn't require a new PR.

**Comment by distantnative** [comment]
@texnixe but the controller seems to be missing

```
Undefined variable $kirbyVersion
```

**Comment by texnixe** [comment]
@distantnative Oh my, was doing this quickly during lunch break and forgot to add the controller to the commit 😢

**Review by distantnative — APPROVED** [review]

**Pull request merged**
