### PR TITLE
Remove deprecated plugins

### PR DESCRIPTION
**Pull request by texnixe**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
The auto compression is really getting on my nerves. @lukasbestle @distantnative what's the best way to undo it here? It's not even related to the PR.

**Comment by distantnative** [comment]
@bastianallgeier I'd suggest to really just remove the workflow for now. It annoys me more than it helps

**Comment by bastianallgeier** [comment]
Could this be a manual workflow? I think that would be ideal.

**Comment by afbora** [comment]
I'm not sure but may be you interest: https://imgbot.net/ (I have not used it and do not know all its features. We can consider it as an alternative solution.)

**Comment by distantnative** [comment]
@bastianallgeier manual can be configured, yes: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

**Pull request merged**
