### PR TITLE
Docs for a::update()

### PR DESCRIPTION
**Pull request by distantnative**

### CODE REVIEW

**Comment by lukasbestle** [comment]
Thanks! Two small issues however:

- Please don't use the `Call` field for new documentation (see the style guide).
- A simple example would be great. :)

**Comment by distantnative** [comment]
Ah, I just copied a::merge() and modified it

**Comment by JimmyRittenborg** [comment]
A tiny typo in "he second parameter"

**Comment by distantnative** [comment]
Fixed and added examples.

**Pull request merged**
