### PR TITLE
Texnixe/oop

### PR DESCRIPTION
**Pull request by texnixe**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
@texnixe why did you close the PR?

**Comment by texnixe** [comment]
@bastianallgeier Because I first wanted to proof-read it again and then I thought I could add a thought or two here and there. But feedback welcome!

**Comment by bastianallgeier** [comment]
Ok, no problem. I will wait a bit more in this case.

**Comment by texnixe** [comment]
@bastianallgeier Do you think it's useful?

**Comment by bastianallgeier** [comment]
Yes, absolutely! I think our docs would really stand out even more if we give PHP beginners more guidance.

**Comment by texnixe** [comment]
That was the idea. Another one I've started is using Xdebug.

**Pull request closed without merging**
