### PR TITLE
Update cheatsheet-article.txt

### PR DESCRIPTION
**Pull request by S1SYPHOS**

### CODE REVIEW

**Comment by distantnative** [comment]
I don't think this would work (toggle field with options)

**Comment by afbora** [comment]
It works but without reading `options` :)) doesn't need anyway. 
In order not to get confused, `options` should be removed.

**Comment by S1SYPHOS** [comment]
Changed it already .. waiting for it to show up ...

**Comment by S1SYPHOS** [comment]
Well, now there are two of them - never should have tried GitHub direct GUI editing ..

**Comment by distantnative** [comment]
Is this actually about an inaccuracy or just a personal preference to rather use `toggle` instead of `radio`?

**Comment by S1SYPHOS** [comment]
From my PoV it's about consistency.

**Comment by distantnative** [comment]
@S1SYPHOS consistency in what sense? I'm not sure I understand

**Comment by S1SYPHOS** [comment]
@distantnative Well, looking at it now, it might as well be a radio, but ..

1. the other "switch" in the article is a toggle, too (consistency)
2. semantically, a toggle (between **only two** states) makes more sense imho

**Comment by texnixe** [comment]
Personally, I think these are different examples altogether, so consistency is probably not necessary here. It's always good to show different options.

A toggle is sometimes harder to understand for some people, who'd probably prefer to use a radio field or a checkbox for only two options. So I don't think that the only option for choosing between two options should necessarily be a toggle field.

**Comment by distantnative** [comment]
I agree, let's stick with the radio field for this example.

**Pull request closed without merging**
