### PR TITLE
Add Typographer plugin

### PR DESCRIPTION
**Pull request by nilshoerrmann**
This PR adds our Typographer plugin to the directory.

### CODE REVIEW

**Review by texnixe — COMMENTED** [review]
Could you please add the `Published` field with today's date? For some reason I cannot edit the file myself. Thanks!

**Comment by nilshoerrmann** [comment]
Do the other plugins need that as well because I don't see that field there either?

**Comment by texnixe** [comment]
We only added the field a while ago, doesn't make sense for old plugins. The purpose is to show new plugins for 6 weeks in the `new` category.

**Comment by nilshoerrmann** [comment]
Hm, seems like something is not correct with my content file: the image is not displaying in the overview and there is no content on the plugin's page: https://getkirby.com/plugins/hananils/typographer

Any idea what I'd have to change to correct this?

**Comment by texnixe** [comment]
File name is wrong, must be plugin.txt not default.txt

**Pull request merged**
