### PR TITLE
Added return field to cheatsheet items in 0-page

### PR DESCRIPTION
**Pull request by benseitz**
Some hasX functions (eg hasNext()) return a boolean, but others (eg hasFiles()) use the count function and return a string?
And a formated Timestamp returns a string, while the timestamp-return-value is an integer?

### CODE REVIEW

**Comment by bastianallgeier** [comment]
hasFiles() should not return a string but an integer, but it might make sense to convert that to a simple boolean. The date method returning an integer is intended for timestamps. Thanks for the massive update!

**Comment by benseitz** [comment]
Oh, I meant integer of course! And thats why's there the bool()-helper :)

Your comments in toolkit/lib/exif.php say, that the timestamp is returned as a string?

**Comment by bastianallgeier** [comment]
The docs in the code might not always be 100% correct. I'm trying to be careful here, but it's a lot of code and I sometimes simply miss things :)

**Comment by benseitz** [comment]
Ahh, no problem ;)

**Pull request merged**
