### PR TITLE
Add Plainkit to Try page

### LINKED ISSUE #760: Try page: Offer Plaintkit side-by-side with Starterkit
@bastianallgeier and I talked with some developers about how the starterkit isn't really anymore the one to pick when starting a new project as it features so much example code, documentation etc.

I think, we should emphasize the plaint more as the go-to download for new projects and clearly highlight the starterkit more as an entry point for new developers to learn about Kirby, play around, explore... but not for starting new projects necessarily.

### LINKED ISSUE #809: Try: link to "get running guide"

### LINKED ISSUE #810: News: add Kosmos thumbs and teaser
Let's start with pulling in the first image as a preview

### PR DESCRIPTION
**Pull request by distantnative**
Fixes #760 
Fixes #809 

**Try page:**

Screen Shot 2020-01-14 at 20 52 48

**Get running guide:**

Screen Shot 2020-01-14 at 20 50 23

### CODE REVIEW

**Comment by texnixe** [comment]
Looks good, I'm just wondering if the two buttons shouldn't look the same on both pages. And maybe we should change `newbies` to `new users`?

**Comment by distantnative** [comment]
@texnixe Somehow adding the icon to the button in the guide breaks the whole button and everything around it :(

**Comment by texnixe** [comment]
@distantnative If we put the same HTML code from the try page instead of the Markdown stuff into `kits.php`, it should work (replacing the columns with plain HTML as well). 

```
<div class="columns columns-2">
  <div class="column">

    <p class="-align:center -mb:huge">
      <?php snippet('cta', [
        'link' => 'https://download.getkirby.com',
        'text' => 'Starterkit',
        'icon' => 'download',
      ]) ?>
    </p>
    <p>The Starterkit is a full-blown Kirby installation with a lot of example content, blueprints, templates and more. It is ideal to explore many of Kirby's options and play with the Panel.
    </p>
  </div>
  <div class="column">
    <p class="-align:center -mb:huge">
      <?php snippet('cta', [
        'link' => 'https://github.com/getkirby/plainkit/archive/master.zip',
        'text' => 'Plainkit',
        'icon' => 'download',
      ]) ?>
    </p>
    <p>The Plainkit is a minimal Kirby installation with the basics you need to start a project from scratch. It is the ideal choice if you are already familiar with Kirby or if you want to start step-by-step.
    </p>
  </div>
</div>
```

**Comment by distantnative** [comment]
@texnixe Awesome! Updated with your suggestion. And also replaced newbies.

**Review by texnixe — APPROVED** [review]

**Pull request merged**
