### PR TITLE
Update reference-article.txt

### PR DESCRIPTION
**Pull request by luxuryluke**
I'm guessing this part is missing for this portfolio setup.
Missing the file/cover.yml blueprint for cover images.

Of course, modify this to fit what you'd really like to say.

### CODE REVIEW

**Review by lukasbestle — APPROVED** [review]
Makes sense, thanks!

**Comment by luxuryluke** [comment]
However, i did not test this.

**Comment by texnixe** [comment]
It will actually work as expected even without that file, so to assign a file template, that template doesn't have to exist.

**Comment by lukasbestle** [comment]
@texnixe Is that also the case when changing the file template in v4? I thought that only works with existing blueprints, but I may misremember.

**Comment by luxuryluke** [comment]
Alternatively you could strip the Cover functionality out of this demo and it may be more straightforward and simple.
I loove the cover functionality myself.

**Comment by texnixe** [comment]
@lukasbestle Good point, haven't checked.

**Comment by luxuryluke** [comment]
Also, it mentions one MIN and three MAX cover images here, and that seems odd. Why is Cover used instead of Image, then? Preferences, clarity, etc.
Perhaps a bit of this portfolio code is worth simplifying or revisiting. No pressure at all, though.

**Comment by texnixe** [comment]
@luxuryluke I agree.

**Pull request merged**
