### PR TITLE
Refactor objects/classes in Reference

### PR DESCRIPTION
**Pull request by distantnative**
Screen Shot 2021-04-18 at 14 12 46

Our Reference setup for objects has been quite complicated:

- some are mixed auto/manually documented at `docs/reference/objects`
- others are mixed auto/manually documented at `docs/reference/tools`
- the rest it auto generated at `docs/reference/@/classes`

**What are we changing**
- all classes are now located at `docs/reference/objects`, e.g. `docs/reference/objects/cms/file`
- this allows us to add manual docs also to classes/methods that aren't shown in the sidebar
- new way (`reference-quicklinks` model) to add sidebar links that point to the actual unlisted classes
- new way (`separator` template) to add pages in the sidebar that get rendered as `<hr>`

I tried to split up the PR into smaller commit, especially to separate the content file moving changes which are a lot.

Screen Shot 2021-04-18 at 14 16 26

## Todo

- [x] Redirects for old URLs
- [x] Figure out how to handle in meta and search

### CODE REVIEW

**Comment by bastianallgeier** [comment]
This is great! I think we should include $site in the list of main objects though. I was also wondering, what do you think about introducing another main point "Collections" 

## Objects
- $kirby
- $page
- $file
- $site
- $user
***
- $pagination
- $block
- $layout
- $request
- $session

## Collections
- $files
- $pages
- $users
***
- $blocks
- $layouts
- $languages


Not sure if it's too much though.

**Comment by distantnative** [comment]
$site should be there, total oversight on my side!

I'm not sure if it'll help to put $page and $pages in different sections. Er might think of them abstract as collections but for most people they go hand in hand together, much more than the different models.

**Comment by bastianallgeier** [comment]
You are right. Let's add site and leave it like that. The rest is already super cool!

**Comment by distantnative** [comment]
@bastianallgeier added $site

**Review by bastianallgeier — APPROVED** [review]

**Pull request merged**
