### PR TITLE
Code: fix overflowing shadow on Copy #1070

### PR DESCRIPTION
**Pull request by distantnative**
Fixes this:
100333614-190fc180-2fd3-11eb-9a0b-0b2615e8a992

### CODE REVIEW

**Comment by afbora** [comment]
This issue seems to continue for me. Is it normal for it to look like the screenshot?

Ekran Resmi 2021-01-17 17 25 45

**Comment by distantnative** [comment]
It's not ideal but better than originally:
- originally the shadow would reach outside of the code element
- in your case it is actually still contained in the code element, just that the code element itself has a scrollbar and it overlaps the scrollbar. 

Not sure how we could fix your case too.

**Comment by afbora** [comment]
What if we prevented the selection of text with CSS?

````css
-webkit-touch-callout: none; /* iOS Safari */
  -webkit-user-select: none; /* Safari */
   -khtml-user-select: none; /* Konqueror HTML */
     -moz-user-select: none; /* Old versions of Firefox */
      -ms-user-select: none; /* Internet Explorer/Edge */
          user-select: none; /* Non-prefixed version, currently supported by Chrome, Edge, Opera and Firefox */
````

**Comment by lukasbestle** [comment]
@afbora Do you mean on the "Copy" button? Sure, why not. :)

**Comment by lukasbestle** [comment]
Regarding the shadow: Maybe we could use a less aggressive shadow that doesn't reach as far.

**Comment by afbora** [comment]
> Do you mean on the "Copy" button? Sure, why not. :)

@lukasbestle Yes on the copy button 😉

**Comment by distantnative** [comment]
@afbora oh yes that we can do! I thought you meant the shadow, not the selection.

@lukasbestle As far as I understand @bastianallgeier or @fabianmichael added the gradient not for the copy button but to fade out any text lines reaching outside the box, to not be clipped directly at the border but also hint a bit more towards that there's more when scrolling right.

**Comment by fabianmichael** [comment]
@distantnative The shadow was in fact placed there to prevent any collisions with the copy button. I don’t know if the bug was introduced with a code/design change or if I just forgot to test with single-liners, when we started. I tested different shadow sizes for the button backdrop and this one resulted in the most subtle look – at least as long as the shadow does not exceed the code block. 

So if you got a better solution (maybe a black outline around the button would also work), please go ahead!

**Comment by lukasbestle** [comment]
Maybe we could combine an outline with a smaller shadow (smaller blur radius).

**Comment by distantnative** [comment]
Maybe we should solve this in the new CSS setup then that Bastian is working on instead. And leave it in the current/old code for now.

**Comment by lukasbestle** [comment]
Yep, I agree. It doesn't make sense to work on this twice.

**Comment by distantnative** [comment]
I think I would still merge this PR, it makes the visual bug slightly better for now.

**Pull request closed without merging**
